output   = "models"
wipe     = true
no-tests = true
add-enum-types = true

[mysql]
  dbname  = "BulletinBoard"
  host    = "localhost"
  port    = 3306
  user    = "root"
  pass    = "my-secret-pw"
  sslmode = "false"