@startuml

package "entities" {
	class "BulletinBoard" as entities.BulletinBoard <<V,Orchid>> {
		+ID: entities.BulletinBoardIDer
		+Title: string
		+Threads: []entities.Thread
	}
}

	entities.BulletinBoard --> entities.BulletinBoardIDer
	entities.BulletinBoard --> entities.Thread


package "entities" {
	interface "BulletinBoardIDer" as entities.BulletinBoardIDer {
		+Equals(id: valueobjects.BulletinBoardID): bool
		+Get(): valueobjects.BulletinBoardID
		+String(): string
	}
}


	entities.BulletinBoardIDer ..> valueobjects.BulletinBoardID : <<use>> 
	entities.BulletinBoardIDer ..> valueobjects.BulletinBoardID : <<return>> 

package "entities" {
	class "Comment" as entities.Comment <<V,Orchid>> {
		+ID: entities.CommentIDer
		+ThreadID: entities.ThreadIDer
		+Text: string
		+CreateAt: entities.CommentTimer
	}
}

	entities.Comment --> entities.CommentIDer
	entities.Comment --> entities.ThreadIDer
	entities.Comment --> entities.CommentTimer


package "entities" {
	interface "CommentIDer" as entities.CommentIDer {
		+Get(): valueobjects.CommentID
		+String(): string
	}
}


	entities.CommentIDer ..> valueobjects.CommentID : <<return>> 

package "entities" {
	interface "CommentTimer" as entities.CommentTimer {
		+Equals(ct: valueobjects.CommentTime): bool
		+Get(): valueobjects.CommentTime
		+ToUnixTime(): int64
	}
}


	entities.CommentTimer ..> valueobjects.CommentTime : <<use>> 
	entities.CommentTimer ..> valueobjects.CommentTime : <<return>> 

package "entities" {
	class "Thread" as entities.Thread <<V,Orchid>> {
		+ID: entities.ThreadIDer
		+BulletinBoardID: entities.BulletinBoardIDer
		+Title: string
		+Comments: []entities.Comment
	}
}

	entities.Thread --> entities.ThreadIDer
	entities.Thread --> entities.BulletinBoardIDer
	entities.Thread --> entities.Comment


package "entities" {
	interface "ThreadIDer" as entities.ThreadIDer {
		+Equals(id: valueobjects.ThreadID): bool
		+Get(): valueobjects.ThreadID
		+String(): string
	}
}


	entities.ThreadIDer ..> valueobjects.ThreadID : <<use>> 
	entities.ThreadIDer ..> valueobjects.ThreadID : <<return>> 

package "valueobjects" {
	class "BulletinBoardID" as valueobjects.BulletinBoardID <<V,Orchid>> {
		-id: valueobjects.bulletinBoardID
		-str: string
		+Get(): valueobjects.BulletinBoardID
		+String(): string
		+Equals(other: valueobjects.BulletinBoardID): bool
	}
}

	valueobjects.BulletinBoardID --> valueobjects.bulletinBoardID

	valueobjects.BulletinBoardID ..> valueobjects.BulletinBoardID : <<return>> 
	valueobjects.BulletinBoardID ..> valueobjects.BulletinBoardID : <<use>> 

package "valueobjects" {
	class "CommentID" as valueobjects.CommentID <<V,Orchid>> {
		-id: valueobjects.commentID
		-str: string
		+Get(): valueobjects.CommentID
		+String(): string
		+Equals(other: valueobjects.CommentID): bool
	}
}

	valueobjects.CommentID --> valueobjects.commentID

	valueobjects.CommentID ..> valueobjects.CommentID : <<return>> 
	valueobjects.CommentID ..> valueobjects.CommentID : <<use>> 

package "valueobjects" {
	class "CommentTime" as valueobjects.CommentTime <<V,Orchid>> {
		-unixTime: int64
		+Get(): valueobjects.CommentTime
		+ToUnixTime(): int64
		+Equals(other: valueobjects.CommentTime): bool
	}
}


	valueobjects.CommentTime ..> valueobjects.CommentTime : <<return>> 
	valueobjects.CommentTime ..> valueobjects.CommentTime : <<use>> 

package "valueobjects" {
	class "ThreadID" as valueobjects.ThreadID <<V,Orchid>> {
		-id: valueobjects.threadID
		-str: string
		+Get(): valueobjects.ThreadID
		+String(): string
		+Equals(other: valueobjects.ThreadID): bool
	}
}

	valueobjects.ThreadID --> valueobjects.threadID

	valueobjects.ThreadID ..> valueobjects.ThreadID : <<return>> 
	valueobjects.ThreadID ..> valueobjects.ThreadID : <<use>> 

package "valueobjects" {
	class "bulletinBoardID" as valueobjects.bulletinBoardID <<V,Orchid>>
}



package "valueobjects" {
	class "commentID" as valueobjects.commentID <<V,Orchid>>
}



package "valueobjects" {
	class "threadID" as valueobjects.threadID <<V,Orchid>>
}



package "usecases" {
	interface "BulletinBoardRepositorer" as usecases.BulletinBoardRepositorer {
		+AddBulletinBoard(bb: entities.BulletinBoard): error
		+DeleteBulletinBoard(): error
		+GetBulletinBoardByID(ID: valueobjects.BulletinBoardID): (entities.BulletinBoard, error)
		+ListBulletinBoard(): (entities.BulletinBoard, error)
	}
}


	usecases.BulletinBoardRepositorer ..> entities.BulletinBoard : <<use>> 
	usecases.BulletinBoardRepositorer ..> valueobjects.BulletinBoardID : <<use>> 
	usecases.BulletinBoardRepositorer ..> entities.BulletinBoard : <<return>> 
	usecases.BulletinBoardRepositorer ..> entities.BulletinBoard : <<return>> 

package "usecases" {
	class "BulletinBoardUsecase" as usecases.BulletinBoardUsecase <<E,#FFCC00>> {
		+BulletinBoardRepository: usecases.BulletinBoardRepositorer
		+ThreadRepository: usecases.ThreadRepositorer
		+GetBulletinBoardByID(ID: valueobjects.BulletinBoardID): (entities.BulletinBoard, error)
		+AddBulletinBoard(bb: entities.BulletinBoard): error
		+ListBulletinBoard(): (entities.BulletinBoard, error)
	}
}

	usecases.BulletinBoardUsecase --> usecases.BulletinBoardRepositorer
	usecases.BulletinBoardUsecase --> usecases.ThreadRepositorer

	usecases.BulletinBoardUsecase ..> valueobjects.BulletinBoardID : <<use>> 
	usecases.BulletinBoardUsecase ..> entities.BulletinBoard : <<return>> 
	usecases.BulletinBoardUsecase ..> entities.BulletinBoard : <<use>> 
	usecases.BulletinBoardUsecase ..> entities.BulletinBoard : <<return>> 

package "usecases" {
	interface "CommentRepositorer" as usecases.CommentRepositorer {
		+AddComment(c: entities.Comment): error
		+ListComment(): (entities.Comment, error)
		+ListCommentByThreadID(tID: valueobjects.ThreadID): (entities.Comment, error)
	}
}


	usecases.CommentRepositorer ..> entities.Comment : <<use>> 
	usecases.CommentRepositorer ..> entities.Comment : <<return>> 
	usecases.CommentRepositorer ..> valueobjects.ThreadID : <<use>> 
	usecases.CommentRepositorer ..> entities.Comment : <<return>> 

package "usecases" {
	class "CommentUsecase" as usecases.CommentUsecase <<E,#FFCC00>> {
		+CommentRepository: usecases.CommentRepositorer
		+ThreadRepository: usecases.ThreadRepositorer
		+AddComment(c: entities.Comment): error
		+ListComment(): (entities.Comment, error)
		+ListCommentByThreadID(tID: valueobjects.ThreadID): (entities.Comment, error)
	}
}

	usecases.CommentUsecase --> usecases.CommentRepositorer
	usecases.CommentUsecase --> usecases.ThreadRepositorer

	usecases.CommentUsecase ..> entities.Comment : <<use>> 
	usecases.CommentUsecase ..> entities.Comment : <<return>> 
	usecases.CommentUsecase ..> valueobjects.ThreadID : <<use>> 
	usecases.CommentUsecase ..> entities.Comment : <<return>> 

package "usecases" {
	interface "ThreadRepositorer" as usecases.ThreadRepositorer {
		+AddThread(t: entities.Thread): error
		+GetThreadByID(ID: valueobjects.ThreadID): (entities.Thread, error)
		+ListThread(): (entities.Thread, error)
		+ListThreadByBulletinBoardID(bID: valueobjects.BulletinBoardID): (entities.Thread, error)
	}
}


	usecases.ThreadRepositorer ..> entities.Thread : <<use>> 
	usecases.ThreadRepositorer ..> valueobjects.ThreadID : <<use>> 
	usecases.ThreadRepositorer ..> entities.Thread : <<return>> 
	usecases.ThreadRepositorer ..> entities.Thread : <<return>> 
	usecases.ThreadRepositorer ..> valueobjects.BulletinBoardID : <<use>> 
	usecases.ThreadRepositorer ..> entities.Thread : <<return>> 

package "usecases" {
	class "ThreadUsecase" as usecases.ThreadUsecase <<E,#FFCC00>> {
		+ThreadRepository: usecases.ThreadRepositorer
		+BulletinBoardRepository: usecases.BulletinBoardRepositorer
		+CommentRepository: usecases.CommentRepositorer
		+GetThreadByID(ID: valueobjects.ThreadID): (entities.Thread, error)
		+AddThread(t: entities.Thread): error
		+ListThread(): (entities.Thread, error)
		+ListThreadByBulletinBoardID(bID: valueobjects.BulletinBoardID): (entities.Thread, error)
	}
}

	usecases.ThreadUsecase --> usecases.ThreadRepositorer
	usecases.ThreadUsecase --> usecases.BulletinBoardRepositorer
	usecases.ThreadUsecase --> usecases.CommentRepositorer

	usecases.ThreadUsecase ..> valueobjects.ThreadID : <<use>> 
	usecases.ThreadUsecase ..> entities.Thread : <<return>> 
	usecases.ThreadUsecase ..> entities.Thread : <<use>> 
	usecases.ThreadUsecase ..> entities.Thread : <<return>> 
	usecases.ThreadUsecase ..> valueobjects.BulletinBoardID : <<use>> 
	usecases.ThreadUsecase ..> entities.Thread : <<return>> 

package "controllers" {
	class "BulletinBoard" as controllers.BulletinBoard <<V,Orchid>> {
		+ID: string
		+Title: string
	}
}



package "controllers" {
	class "BulletinBoardController" as controllers.BulletinBoardController <<V,Orchid>> {
		-bbu: usecases.BulletinBoardUsecase
		+GetBulletinBoardByID(ID: string): (entities.BulletinBoard, error)
		+AddBulletinBoard(c: gin.Context): (entities.BulletinBoard, error)
		+ListBulletinBoard(): (entities.BulletinBoard, error)
	}
}

	controllers.BulletinBoardController --> usecases.BulletinBoardUsecase

	controllers.BulletinBoardController ..> entities.BulletinBoard : <<return>> 
	controllers.BulletinBoardController ..> entities.BulletinBoard : <<return>> 
	controllers.BulletinBoardController ..> entities.BulletinBoard : <<return>> 

package "controllers" {
	class "Comment" as controllers.Comment <<V,Orchid>> {
		+ID: string
		+ThreadID: string
		+Text: string
	}
}



package "controllers" {
	class "CommentController" as controllers.CommentController <<V,Orchid>> {
		-cu: usecases.CommentUsecase
		+AddComment(c: gin.Context): (entities.Comment, error)
		+ListComment(): (entities.Comment, error)
		+ListCommentByThreadID(tID: string): (entities.Comment, error)
	}
}

	controllers.CommentController --> usecases.CommentUsecase

	controllers.CommentController ..> entities.Comment : <<return>> 
	controllers.CommentController ..> entities.Comment : <<return>> 
	controllers.CommentController ..> entities.Comment : <<return>> 

package "controllers" {
	class "Thread" as controllers.Thread <<V,Orchid>> {
		+ID: string
		+BulletinBoardID: string
		+Title: string
	}
}



package "controllers" {
	class "ThreadController" as controllers.ThreadController <<V,Orchid>> {
		-tu: usecases.ThreadUsecase
		+GetThreadByID(ID: string): (entities.Thread, error)
		+AddThread(c: gin.Context): (entities.Thread, error)
		+ListThread(): (entities.Thread, error)
		+ListThreadByBulletinBoardID(bID: string): (entities.Thread, error)
	}
}

	controllers.ThreadController --> usecases.ThreadUsecase

	controllers.ThreadController ..> entities.Thread : <<return>> 
	controllers.ThreadController ..> entities.Thread : <<return>> 
	controllers.ThreadController ..> entities.Thread : <<return>> 
	controllers.ThreadController ..> entities.Thread : <<return>> 

package "logger" {
	class "LogColumns" as logger.LogColumns <<E,#FFCC00>> {
		+PID: string
		+UA: string
		+Path: string
		+Body: []byte
		+Error(c: gin.Context, msg: interface{})
		+Info(c: gin.Context, msg: interface{})
		+Debug(c: gin.Context, msg: interface{})
		+Warn(c: gin.Context, msg: interface{})
	}
}



package "logger" {
	interface "Logger" as logger.Logger {
		+Debug(c: *context.Context, msg: interface{})
		+Error(c: *context.Context, msg: interface{})
		+Info(c: *context.Context, msg: interface{})
		+Warn(c: *context.Context, msg: interface{})
	}
}



package "presenters" {
	class "BulletinBoard" as presenters.BulletinBoard <<V,Orchid>> {
		+ID: string
		+Title: string
		+Threads: []presenters.Thread
	}
}

	presenters.BulletinBoard --> presenters.Thread


package "presenters" {
	class "BulletinBoardPresenter" as presenters.BulletinBoardPresenter <<V,Orchid>> {
		+ConvertToHTTPBulletinBoardListResponse(bbl: entities.BulletinBoard): *presenters.HTTPResponse
		+ConvertToHTTPBulletinBoardResponse(bb: entities.BulletinBoard): *presenters.HTTPResponse
	}
}


	presenters.BulletinBoardPresenter ..> entities.BulletinBoard : <<use>> 
	presenters.BulletinBoardPresenter ..> presenters.HTTPResponse : <<return>> 
	presenters.BulletinBoardPresenter ..> entities.BulletinBoard : <<use>> 
	presenters.BulletinBoardPresenter ..> presenters.HTTPResponse : <<return>> 

package "presenters" {
	class "Comment" as presenters.Comment <<V,Orchid>> {
		+ID: string
		+ThreadID: string
		+Text: string
		+CreatAt: int64
	}
}



package "presenters" {
	class "CommentPresenter" as presenters.CommentPresenter <<V,Orchid>> {
		+ConvertToHTTPCommentListResponse(cl: entities.Comment): *presenters.HTTPResponse
		+ConvertToHTTPCommentResponse(c: entities.Comment): *presenters.HTTPResponse
	}
}


	presenters.CommentPresenter ..> entities.Comment : <<use>> 
	presenters.CommentPresenter ..> presenters.HTTPResponse : <<return>> 
	presenters.CommentPresenter ..> entities.Comment : <<use>> 
	presenters.CommentPresenter ..> presenters.HTTPResponse : <<return>> 

package "presenters" {
	class "ErrorPresenter" as presenters.ErrorPresenter <<V,Orchid>> {
		+ConvertToHTTPErrorResponse(err: error): *presenters.HTTPResponse
	}
}


	presenters.ErrorPresenter ..> presenters.HTTPResponse : <<return>> 

package "presenters" {
	class "HTTPResponse" as presenters.HTTPResponse <<V,Orchid>> {
		+Items: interface{}
	}
}



package "presenters" {
	class "Thread" as presenters.Thread <<V,Orchid>> {
		+ID: string
		+BulletinBoardID: string
		+Title: string
		+Comments: []presenters.Comment
	}
}

	presenters.Thread --> presenters.Comment


package "presenters" {
	class "ThreadPresenter" as presenters.ThreadPresenter <<V,Orchid>> {
		+ConvertToHTTPThreadListResponse(tl: entities.Thread): *presenters.HTTPResponse
		+ConvertToHTTPThreadResponse(t: entities.Thread): *presenters.HTTPResponse
	}
}


	presenters.ThreadPresenter ..> entities.Thread : <<use>> 
	presenters.ThreadPresenter ..> presenters.HTTPResponse : <<return>> 
	presenters.ThreadPresenter ..> entities.Thread : <<use>> 
	presenters.ThreadPresenter ..> presenters.HTTPResponse : <<return>> 

package "api" {
	class "Router" as api.Router <<E,#FFCC00>> {
		+BulletinBoardController: controllers.BulletinBoardController
		+BulletinBoardPresenter: presenters.BulletinBoardPresenter
		+ThreadController: controllers.ThreadController
		+ThreadPresenter: presenters.ThreadPresenter
		+CommentController: controllers.CommentController
		+CommentPresenter: presenters.CommentPresenter
		+ErrorPresenter: presenters.ErrorPresenter
		-responseByError(c: gin.Context, err: error)
		-postThread(c: gin.Context)
		-getThreadByID(c: gin.Context)
		-listThread(c: gin.Context)
		-listBulletinBoard(c: gin.Context)
		-getBulletinBoardByID(c: gin.Context)
		-postBulletinBoard(c: gin.Context)
		-postComment(c: gin.Context)
		-listComment(c: gin.Context)
	}
}

	api.Router --> controllers.BulletinBoardController
	api.Router --> presenters.BulletinBoardPresenter
	api.Router --> controllers.ThreadController
	api.Router --> presenters.ThreadPresenter
	api.Router --> controllers.CommentController
	api.Router --> presenters.CommentPresenter
	api.Router --> presenters.ErrorPresenter


package "gateways" {
	class "InMemoryRepository" as gateways.InMemoryRepository <<E,#FFCC00>> {
		+GetBulletinBoardByID(ID: valueobjects.BulletinBoardID): (entities.BulletinBoard, error)
		+AddBulletinBoard(b: entities.BulletinBoard): error
		+ListBulletinBoard(): (entities.BulletinBoard, error)
		+ListThread(): (entities.Thread, error)
		+ListThreadByBulletinBoardID(bID: valueobjects.BulletinBoardID): (entities.Thread, error)
		+GetThreadByID(ID: valueobjects.ThreadID): (entities.Thread, error)
		+AddThread(t: entities.Thread): error
		+ListComment(): (entities.Comment, error)
		+ListCommentByThreadID(tID: valueobjects.ThreadID): (entities.Comment, error)
		+AddComment(c: entities.Comment): error
		+DeleteAll()
		+DeleteBulletinBoard(): error
		+DeleteThread()
		+DeleteComment()
	}
}


	gateways.InMemoryRepository ..> valueobjects.BulletinBoardID : <<use>> 
	gateways.InMemoryRepository ..> entities.BulletinBoard : <<return>> 
	gateways.InMemoryRepository ..> entities.BulletinBoard : <<use>> 
	gateways.InMemoryRepository ..> entities.BulletinBoard : <<return>> 
	gateways.InMemoryRepository ..> entities.Thread : <<return>> 
	gateways.InMemoryRepository ..> valueobjects.BulletinBoardID : <<use>> 
	gateways.InMemoryRepository ..> entities.Thread : <<return>> 
	gateways.InMemoryRepository ..> valueobjects.ThreadID : <<use>> 
	gateways.InMemoryRepository ..> entities.Thread : <<return>> 
	gateways.InMemoryRepository ..> entities.Thread : <<use>> 
	gateways.InMemoryRepository ..> entities.Comment : <<return>> 
	gateways.InMemoryRepository ..> valueobjects.ThreadID : <<use>> 
	gateways.InMemoryRepository ..> entities.Comment : <<return>> 
	gateways.InMemoryRepository ..> entities.Comment : <<use>> 

package "configs" {
	class "Config" as configs.Config <<V,Orchid>> {
		+Environment: string
	}
}



package "configs" {
	interface "Configer" as configs.Configer {
		+Get(): configs.Config
	}
}


	configs.Configer ..> configs.Config : <<return>> 

package "configs" {
	class "OsConfig" as configs.OsConfig <<V,Orchid>> {
		-config: configs.Config
		+Get(): configs.Config
	}
}

	configs.OsConfig --> configs.Config

	configs.OsConfig ..> configs.Config : <<return>> 

package "configs" {
	class "YamlConfig" as configs.YamlConfig <<V,Orchid>> {
		-config: configs.Config
		+Get(): configs.Config
	}
}

	configs.YamlConfig --> configs.Config

	configs.YamlConfig ..> configs.Config : <<return>> 

package "errorobjects" {
	class "CharacterSizeValidationError" as errorobjects.CharacterSizeValidationError <<V,Orchid>> {
		-msg: string
		-code: int
		+Error(): string
	}
}



package "errorobjects" {
	class "InternalServerError" as errorobjects.InternalServerError <<V,Orchid>> {
		-msg: string
		-code: int
		+Error(): string
	}
}



package "errorobjects" {
	class "MissingRequiredFieldsError" as errorobjects.MissingRequiredFieldsError <<V,Orchid>> {
		-msg: string
		-code: int
		+Error(): string
	}
}



package "errorobjects" {
	class "NotFoundError" as errorobjects.NotFoundError <<V,Orchid>> {
		-msg: string
		-code: int
		+Error(): string
	}
}



package "errorobjects" {
	class "ParameterBindingError" as errorobjects.ParameterBindingError <<V,Orchid>> {
		-msg: string
		-code: int
		+Error(): string
	}
}



package "errorobjects" {
	class "ResourceLimitedError" as errorobjects.ResourceLimitedError <<V,Orchid>> {
		-msg: string
		-code: int
		+Error(): string
	}
}



	usecases.CommentUsecase -up-|> usecases.CommentRepositorer
	usecases.ThreadUsecase -up-|> usecases.ThreadRepositorer
	gateways.InMemoryRepository -up-|> usecases.BulletinBoardRepositorer
	gateways.InMemoryRepository -up-|> usecases.CommentRepositorer
	gateways.InMemoryRepository -up-|> usecases.ThreadRepositorer
	configs.OsConfig -up-|> configs.Configer
	configs.YamlConfig -up-|> configs.Configer


@enduml
