// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Thread is an object representing the database table.
type Thread struct { // ThreadのID
	// UUIDを期待しています
	ID string `boil:"id" json:"id" toml:"id" yaml:"id"`
	// BulletinBoardのID
	// UUIDを期待しています
	BulltienBoardID string `boil:"bulltien_board_id" json:"bulltien_board_id" toml:"bulltien_board_id" yaml:"bulltien_board_id"`
	// Threadのタイトル
	Title string `boil:"title" json:"title" toml:"title" yaml:"title"`
	// CommentのID
	// UUIDを期待しています
	CommentID string `boil:"comment_id" json:"comment_id" toml:"comment_id" yaml:"comment_id"`

	R *threadR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L threadL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ThreadColumns = struct {
	ID              string
	BulltienBoardID string
	Title           string
	CommentID       string
}{
	ID:              "id",
	BulltienBoardID: "bulltien_board_id",
	Title:           "title",
	CommentID:       "comment_id",
}

var ThreadTableColumns = struct {
	ID              string
	BulltienBoardID string
	Title           string
	CommentID       string
}{
	ID:              "Thread.id",
	BulltienBoardID: "Thread.bulltien_board_id",
	Title:           "Thread.title",
	CommentID:       "Thread.comment_id",
}

// Generated where

var ThreadWhere = struct {
	ID              whereHelperstring
	BulltienBoardID whereHelperstring
	Title           whereHelperstring
	CommentID       whereHelperstring
}{
	ID:              whereHelperstring{field: "`Thread`.`id`"},
	BulltienBoardID: whereHelperstring{field: "`Thread`.`bulltien_board_id`"},
	Title:           whereHelperstring{field: "`Thread`.`title`"},
	CommentID:       whereHelperstring{field: "`Thread`.`comment_id`"},
}

// ThreadRels is where relationship names are stored.
var ThreadRels = struct {
	BulltienBoard  string
	ThreadComments string
}{
	BulltienBoard:  "BulltienBoard",
	ThreadComments: "ThreadComments",
}

// threadR is where relationships are stored.
type threadR struct {
	BulltienBoard  *BulletinBoard `boil:"BulltienBoard" json:"BulltienBoard" toml:"BulltienBoard" yaml:"BulltienBoard"`
	ThreadComments CommentSlice   `boil:"ThreadComments" json:"ThreadComments" toml:"ThreadComments" yaml:"ThreadComments"`
}

// NewStruct creates a new relationship struct
func (*threadR) NewStruct() *threadR {
	return &threadR{}
}

func (r *threadR) GetBulltienBoard() *BulletinBoard {
	if r == nil {
		return nil
	}
	return r.BulltienBoard
}

func (r *threadR) GetThreadComments() CommentSlice {
	if r == nil {
		return nil
	}
	return r.ThreadComments
}

// threadL is where Load methods for each relationship are stored.
type threadL struct{}

var (
	threadAllColumns            = []string{"id", "bulltien_board_id", "title", "comment_id"}
	threadColumnsWithoutDefault = []string{"id", "bulltien_board_id", "title", "comment_id"}
	threadColumnsWithDefault    = []string{}
	threadPrimaryKeyColumns     = []string{"id"}
	threadGeneratedColumns      = []string{}
)

type (
	// ThreadSlice is an alias for a slice of pointers to Thread.
	// This should almost always be used instead of []Thread.
	ThreadSlice []*Thread
	// ThreadHook is the signature for custom Thread hook methods
	ThreadHook func(context.Context, boil.ContextExecutor, *Thread) error

	threadQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	threadType                 = reflect.TypeOf(&Thread{})
	threadMapping              = queries.MakeStructMapping(threadType)
	threadPrimaryKeyMapping, _ = queries.BindMapping(threadType, threadMapping, threadPrimaryKeyColumns)
	threadInsertCacheMut       sync.RWMutex
	threadInsertCache          = make(map[string]insertCache)
	threadUpdateCacheMut       sync.RWMutex
	threadUpdateCache          = make(map[string]updateCache)
	threadUpsertCacheMut       sync.RWMutex
	threadUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var threadAfterSelectHooks []ThreadHook

var threadBeforeInsertHooks []ThreadHook
var threadAfterInsertHooks []ThreadHook

var threadBeforeUpdateHooks []ThreadHook
var threadAfterUpdateHooks []ThreadHook

var threadBeforeDeleteHooks []ThreadHook
var threadAfterDeleteHooks []ThreadHook

var threadBeforeUpsertHooks []ThreadHook
var threadAfterUpsertHooks []ThreadHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Thread) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Thread) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Thread) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Thread) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Thread) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Thread) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Thread) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Thread) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Thread) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddThreadHook registers your hook function for all future operations.
func AddThreadHook(hookPoint boil.HookPoint, threadHook ThreadHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		threadAfterSelectHooks = append(threadAfterSelectHooks, threadHook)
	case boil.BeforeInsertHook:
		threadBeforeInsertHooks = append(threadBeforeInsertHooks, threadHook)
	case boil.AfterInsertHook:
		threadAfterInsertHooks = append(threadAfterInsertHooks, threadHook)
	case boil.BeforeUpdateHook:
		threadBeforeUpdateHooks = append(threadBeforeUpdateHooks, threadHook)
	case boil.AfterUpdateHook:
		threadAfterUpdateHooks = append(threadAfterUpdateHooks, threadHook)
	case boil.BeforeDeleteHook:
		threadBeforeDeleteHooks = append(threadBeforeDeleteHooks, threadHook)
	case boil.AfterDeleteHook:
		threadAfterDeleteHooks = append(threadAfterDeleteHooks, threadHook)
	case boil.BeforeUpsertHook:
		threadBeforeUpsertHooks = append(threadBeforeUpsertHooks, threadHook)
	case boil.AfterUpsertHook:
		threadAfterUpsertHooks = append(threadAfterUpsertHooks, threadHook)
	}
}

// One returns a single thread record from the query.
func (q threadQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Thread, error) {
	o := &Thread{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for Thread")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Thread records from the query.
func (q threadQuery) All(ctx context.Context, exec boil.ContextExecutor) (ThreadSlice, error) {
	var o []*Thread

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Thread slice")
	}

	if len(threadAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Thread records in the query.
func (q threadQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count Thread rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q threadQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if Thread exists")
	}

	return count > 0, nil
}

// BulltienBoard pointed to by the foreign key.
func (o *Thread) BulltienBoard(mods ...qm.QueryMod) bulletinBoardQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.BulltienBoardID),
	}

	queryMods = append(queryMods, mods...)

	return BulletinBoards(queryMods...)
}

// ThreadComments retrieves all the Comment's Comments with an executor via thread_id column.
func (o *Thread) ThreadComments(mods ...qm.QueryMod) commentQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`Comment`.`thread_id`=?", o.ID),
	)

	return Comments(queryMods...)
}

// LoadBulltienBoard allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (threadL) LoadBulltienBoard(ctx context.Context, e boil.ContextExecutor, singular bool, maybeThread interface{}, mods queries.Applicator) error {
	var slice []*Thread
	var object *Thread

	if singular {
		var ok bool
		object, ok = maybeThread.(*Thread)
		if !ok {
			object = new(Thread)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeThread)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeThread))
			}
		}
	} else {
		s, ok := maybeThread.(*[]*Thread)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeThread)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeThread))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &threadR{}
		}
		args = append(args, object.BulltienBoardID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &threadR{}
			}

			for _, a := range args {
				if a == obj.BulltienBoardID {
					continue Outer
				}
			}

			args = append(args, obj.BulltienBoardID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`BulletinBoard`),
		qm.WhereIn(`BulletinBoard.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load BulletinBoard")
	}

	var resultSlice []*BulletinBoard
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice BulletinBoard")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for BulletinBoard")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for BulletinBoard")
	}

	if len(threadAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.BulltienBoard = foreign
		if foreign.R == nil {
			foreign.R = &bulletinBoardR{}
		}
		foreign.R.BulltienBoardThreads = append(foreign.R.BulltienBoardThreads, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.BulltienBoardID == foreign.ID {
				local.R.BulltienBoard = foreign
				if foreign.R == nil {
					foreign.R = &bulletinBoardR{}
				}
				foreign.R.BulltienBoardThreads = append(foreign.R.BulltienBoardThreads, local)
				break
			}
		}
	}

	return nil
}

// LoadThreadComments allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (threadL) LoadThreadComments(ctx context.Context, e boil.ContextExecutor, singular bool, maybeThread interface{}, mods queries.Applicator) error {
	var slice []*Thread
	var object *Thread

	if singular {
		var ok bool
		object, ok = maybeThread.(*Thread)
		if !ok {
			object = new(Thread)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeThread)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeThread))
			}
		}
	} else {
		s, ok := maybeThread.(*[]*Thread)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeThread)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeThread))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &threadR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &threadR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`Comment`),
		qm.WhereIn(`Comment.thread_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Comment")
	}

	var resultSlice []*Comment
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Comment")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on Comment")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for Comment")
	}

	if len(commentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ThreadComments = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &commentR{}
			}
			foreign.R.Thread = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ThreadID {
				local.R.ThreadComments = append(local.R.ThreadComments, foreign)
				if foreign.R == nil {
					foreign.R = &commentR{}
				}
				foreign.R.Thread = local
				break
			}
		}
	}

	return nil
}

// SetBulltienBoard of the thread to the related item.
// Sets o.R.BulltienBoard to related.
// Adds o to related.R.BulltienBoardThreads.
func (o *Thread) SetBulltienBoard(ctx context.Context, exec boil.ContextExecutor, insert bool, related *BulletinBoard) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `Thread` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"bulltien_board_id"}),
		strmangle.WhereClause("`", "`", 0, threadPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.BulltienBoardID = related.ID
	if o.R == nil {
		o.R = &threadR{
			BulltienBoard: related,
		}
	} else {
		o.R.BulltienBoard = related
	}

	if related.R == nil {
		related.R = &bulletinBoardR{
			BulltienBoardThreads: ThreadSlice{o},
		}
	} else {
		related.R.BulltienBoardThreads = append(related.R.BulltienBoardThreads, o)
	}

	return nil
}

// AddThreadComments adds the given related objects to the existing relationships
// of the Thread, optionally inserting them as new records.
// Appends related to o.R.ThreadComments.
// Sets related.R.Thread appropriately.
func (o *Thread) AddThreadComments(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Comment) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ThreadID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `Comment` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"thread_id"}),
				strmangle.WhereClause("`", "`", 0, commentPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ThreadID = o.ID
		}
	}

	if o.R == nil {
		o.R = &threadR{
			ThreadComments: related,
		}
	} else {
		o.R.ThreadComments = append(o.R.ThreadComments, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &commentR{
				Thread: o,
			}
		} else {
			rel.R.Thread = o
		}
	}
	return nil
}

// Threads retrieves all the records using an executor.
func Threads(mods ...qm.QueryMod) threadQuery {
	mods = append(mods, qm.From("`Thread`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`Thread`.*"})
	}

	return threadQuery{q}
}

// FindThread retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindThread(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Thread, error) {
	threadObj := &Thread{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `Thread` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, threadObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from Thread")
	}

	if err = threadObj.doAfterSelectHooks(ctx, exec); err != nil {
		return threadObj, err
	}

	return threadObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Thread) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no Thread provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(threadColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	threadInsertCacheMut.RLock()
	cache, cached := threadInsertCache[key]
	threadInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			threadAllColumns,
			threadColumnsWithDefault,
			threadColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(threadType, threadMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(threadType, threadMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `Thread` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `Thread` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `Thread` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, threadPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into Thread")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for Thread")
	}

CacheNoHooks:
	if !cached {
		threadInsertCacheMut.Lock()
		threadInsertCache[key] = cache
		threadInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Thread.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Thread) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	threadUpdateCacheMut.RLock()
	cache, cached := threadUpdateCache[key]
	threadUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			threadAllColumns,
			threadPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update Thread, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `Thread` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, threadPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(threadType, threadMapping, append(wl, threadPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update Thread row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for Thread")
	}

	if !cached {
		threadUpdateCacheMut.Lock()
		threadUpdateCache[key] = cache
		threadUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q threadQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for Thread")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for Thread")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ThreadSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), threadPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `Thread` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, threadPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in thread slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all thread")
	}
	return rowsAff, nil
}

var mySQLThreadUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Thread) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no Thread provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(threadColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLThreadUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	threadUpsertCacheMut.RLock()
	cache, cached := threadUpsertCache[key]
	threadUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			threadAllColumns,
			threadColumnsWithDefault,
			threadColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			threadAllColumns,
			threadPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert Thread, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`Thread`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `Thread` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(threadType, threadMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(threadType, threadMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for Thread")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(threadType, threadMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for Thread")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for Thread")
	}

CacheNoHooks:
	if !cached {
		threadUpsertCacheMut.Lock()
		threadUpsertCache[key] = cache
		threadUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Thread record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Thread) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Thread provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), threadPrimaryKeyMapping)
	sql := "DELETE FROM `Thread` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from Thread")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for Thread")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q threadQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no threadQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from Thread")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for Thread")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ThreadSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(threadBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), threadPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `Thread` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, threadPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from thread slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for Thread")
	}

	if len(threadAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Thread) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindThread(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ThreadSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ThreadSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), threadPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `Thread`.* FROM `Thread` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, threadPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ThreadSlice")
	}

	*o = slice

	return nil
}

// ThreadExists checks if the Thread row exists.
func ThreadExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `Thread` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if Thread exists")
	}

	return exists, nil
}
