// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"bulltienboard/adapters/controllers"
	"bulltienboard/adapters/gateways"
	"bulltienboard/adapters/presenters"
	"bulltienboard/drivers/web/api"
	"bulltienboard/usecases"
)

// Injectors from wire.go:

func InitializeRouter() *api.Router {
	inMemoryRepository := gateways.NewInMemoryRepository()
	bulletinBoardUsecase := usecases.NewBulletinBoardUsecase(inMemoryRepository, inMemoryRepository)
	bulletinBoardController := controllers.NewBulletinBoardController(bulletinBoardUsecase)
	bulletinBoardPresenter := presenters.NewBulletinBoardPresenter()
	threadUsecase := usecases.NewThreadUsecase(inMemoryRepository, inMemoryRepository, inMemoryRepository)
	threadController := controllers.NewThreadController(threadUsecase)
	threadPresenter := presenters.NewThreadPresenter()
	commentUsecase := usecases.NewCommentUsecase(inMemoryRepository, inMemoryRepository)
	commentController := controllers.NewCommentController(commentUsecase)
	commentPresenter := presenters.NewCommentPresenter()
	errorPresenter := presenters.NewErrorPresenter()
	router := api.NewRouter(bulletinBoardController, bulletinBoardPresenter, threadController, threadPresenter, commentController, commentPresenter, errorPresenter)
	return router
}
