// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"vspro/adapters/gateways"
	"vspro/usecases"
)

// Injectors from wire.go:

func GetBulletinBoardUsecase() *usecases.BulletinBoardUsecase {
	inMemoryRepository := gateways.NewInMemoryRepository()
	bulletinBoardUsecase := usecases.NewBulletinBoardUsecase(inMemoryRepository, inMemoryRepository)
	return bulletinBoardUsecase
}

func GetThreadUsecase() *usecases.ThreadUsecase {
	inMemoryRepository := gateways.NewInMemoryRepository()
	threadUsecase := usecases.NewThreadUsecase(inMemoryRepository, inMemoryRepository, inMemoryRepository)
	return threadUsecase
}

func GetCommentUsecase() *usecases.CommentUsecase {
	inMemoryRepository := gateways.NewInMemoryRepository()
	commentUsecase := usecases.NewCommentUsecase(inMemoryRepository, inMemoryRepository)
	return commentUsecase
}
